### PR TITLE
Set up deployments of `packages/server` with Docker and Kamal

### PR DESCRIPTION
**Pull request by wclausen**
Adds kamal initialization folders/files for our deployments to Hetzner servers.

Adds hopefully useful/reasonably concise document outlining the deployment architecture and kamal basics so this can be referenced in the future/you can pipe it to chatty geeps and get back an answer real quick.

### CODE REVIEW

**Review by Melvillian — CHANGES_REQUESTED** [review]
Thanks for the detailed writeup, I feel solid on the bulk of how we'll use kamal and the usual questions I have about infra deployment. I still have a couple questions/requests:

1. Right now this exists at the project root, but shouldn't this go in the `packages/server/` directory, since that's the thing we'll be deploying? I suppose then we'd need one in `web-frontend/` as well, which doesn't deploy any `postgres` or `redis` but just the Svelte app. 

2. Can you add a README.md to the `config/` directory that says the following:

```md
# Kamal Deploy Config

This directory contains all of the deploy and hooks info for our Kamal infra. Currently we use Hetzner as our server provider, and we manage infra deployment with [Kamal](https://kamal-deploy.org/)

## Common Commands

### `kamal env push`

This is an important one to remember, so I'm putting it first. When you write some new code that changes the env variables, that update needs to be proactively pushed to the servers! If you forget this and run `kamal redeploy`, things will not work and may fail in confusing ways. Always run `kamal env push` when you change an environment variable.

### `kamal redeploy`

This will be the primary command you run when interacting with kamal. It will do the following:

- rebuild the docker container for own main app based on your current branch
- push that docker image to our registry
- ssh into the server(s) running that container (behind a traefik load balancer)
- pull the new image
- spin up the new image
- when the new container is healthy, kamal will tell traefik to route to the new container
- kamal will remove the old container

Exactly what you want, nothing you don't. This part I think is fairly straigtforward, though I don't know much about traefik.

### `kamal setup`

If you add a server (due to massive adoption of Habilis), you'll need to run `kamal setup` to make sure it is ready to be managed by kamal. This command basically makes sure docker is present on each of the hosts, then finishes.

### `kamal accessory reboot [name]`

Probably not something you'll run often. But in case redis is on the fritz or you just wanna kick the tires on postgres and see what happens when you turn it off/on again, this is the command to do it. Good to know, but not something I'd expect you or anyone to use regularly.
```

**Comment by willc-lu** [comment]
@Melvillian yep, we do actually need this inside `packages/server`. Fixed that. And added a `README.md` as requested.

Ended up force pushing these changes after rebasing on latest `main`. Here's what I did:

- Moved all the kamal things into `packages/server`
- Updated the `packages/server/config/deploy.yml` (henceforth referred to as `deploy.yml`) to have proper values/config
- Added a `Dockerfile` for packaging the `server` code into a container (inspired by the [bun documentation](https://bun.sh/guides/ecosystem/docker))
- Updated `routes.ts` to include a route that kamal will use for health checks when deploying.
- Ran `kamal setup` to install docker on our two servers and install/run postgres and redis as accessories.
- Debugged and eventually deployed our koa server via `kamal redeploy`
- Verified our DB is live by connecting to it via VSCode's Postgresql Explorer extension

**Comment by willc-lu** [comment]
Visual proof that we have a live server:

image

**Comment by willc-lu** [comment]
ugh wrong account

**Comment by wclausen** [comment]
@Melvillian yep, we do actually need this inside `packages/server`. Fixed that. And added a `README.md` as requested.

Ended up force pushing these changes after rebasing on latest `main`. Here's what I did:

- Moved all the kamal things into `packages/server`
- Updated the `packages/server/config/deploy.yml` (henceforth referred to as `deploy.yml`) to have proper values/config
- Added a `Dockerfile` for packaging the `server` code into a container (inspired by the [bun documentation](https://bun.sh/guides/ecosystem/docker))
- Updated `routes.ts` to include a route that kamal will use for health checks when deploying.
- Ran `kamal setup` to install docker on our two servers and install/run postgres and redis as accessories.
- Debugged and eventually deployed our koa server via `kamal redeploy`
- Verified our DB is live by connecting to it via VSCode's Postgresql Explorer extension

**Comment by wclausen** [comment]
Visual proof that we have a live server:

image

**Review by Melvillian — APPROVED** [review]

**Review by Melvillian — APPROVED** [review]
The docker builds fine for me, and the rest of this looks good to me.

I took a while playing around with the docker image to see if I could make it simpler, but I could not so we'll go as is. It's a little weird to me that we run the the `.ts` file, but it looks like[ it doesn't make a difference to Bun](https://bun.sh/docs/runtime/typescript) so let's do it because I agree it's simpler.

I still need the kamal server passwords to get `kamal redeploy` working, but I'm approving this to unblock you.

**Review by Melvillian — CHANGES_REQUESTED** [review]
Now that my SSH key was added, I'm getting an error about not having access to `wclausen/habilis`. You need to add `melvillian` as a collaborator and then let me know so I can try again.

**Review by Melvillian — APPROVED** [review]

**Comment by Melvillian** [comment]
I'm going to approve and merge because the problem with this PR are purely at the infra auth level, and I want the latest changes made in this PR to go to `main` so I can use them.

**Pull request merged**
